### ISSUE TITLE
java.lang.IllegalArgumentException: Provided artifact is missing a version: [ragtime/ragtime nil]

### ISSUE THREAD

**Issue by minikomi** [mbuczko/boot-ragtime#10]
The order of the `let` here:

https://github.com/mbuczko/boot-ragtime/blob/master/src/mbuczko/boot_ragtime.clj#L20-L23

means that, by default, ragtime-version will be set to `nil`, causing the error in the title of the issue.

**Comment by mbuczko** [comment]
thanks. that was really unfortunate ;)

I already pushed 0.3.1 version which should work fine.
